### ISSUE TITLE
 Awaiting your approbation

### ISSUE THREAD

**Issue by TheNickoos** [VenomXNL/XNL-FiveM-Trains-U3#6]
Seem you haven't see my message on fivem's forum :

I think I will ‘take over’ your project because, as you say, you no longer working on it.

Ofc, I will still let your name in it. That’s your work, and you did well.
I will make another post for the project.

Awaiting your approbation before starting it

**Comment by VenomXNL** [comment]
No problem, Mine was also inspired/based on another person their attempt to make something like this,
unfortunately i never had the time to truly finish this one like i wanted it to be,
So hoping you will have the time to do so :)

**Comment by TheNickoos** [comment]
Thanks a lot !
