### ISSUE TITLE
Trains spawned but won't move

### ISSUE THREAD

**Issue by wanderrer** [VenomXNL/XNL-FiveM-Trains-U3#8]
Hello,
looks like there is a problem with this great resource, while OneSync is enabled. The train spawns also the trams, however they won't move 👍 

![image](https://user-images.githubusercontent.com/63644849/94202446-53bb8780-fec6-11ea-826f-6dbd0b2e01df.png)

**Comment by VenomXNL** [comment]
Sorry I didn't noticed your message until now, my bad.

This is however a known problem :(

I have been working on some new features and will see if i find some time to make some sort of (NEW though!) release out of it.

Meanwhile someone else had 'adopted' this script for onesync which can be found at my FiveM forum page.

But please do keep in mind that spawning the trains like this script does, does actually cause problems anyways.


I have found (and tested) MUCH better methods, but will not (again) release something until i'm absolutely certain that it works as intended this time ;)
